### PR TITLE
Task cancellation fix

### PR DESCRIPTION
**Pull request by mizax**
originally bot tasks does not end when error occurs and bot "restarts", that leads to task duplicating and mad behavior

### CODE REVIEW

**Comment by mizax** [comment]
bot should now behave more stable, testing now
trying to fix infinite recycling issue

**Comment by mizax** [comment]
console input hangs restart, moved it to separate task, will test overnight, push if everything is ok

**Comment by Yishaqel** [comment]
How can I download this with git?

**Comment by mizax** [comment]
@tr1p0z you can get it from my repo https://github.com/mizax/HaxtonBot from task-cancellation-fix branch

**Comment by d-haxton** [comment]
please resolve conflicts then commit again

**Comment by umlucasribeiro** [comment]
captura de tela 2016-08-12 as 06 55 34

Somebody can help me?

**Pull request closed without merging**
