### PR TITLE
added support for linux with mono

### PR DESCRIPTION
**Pull request by christoabrown**
Building works with Visual Studio and xbuild and supports both Windows and Linux. Tested on most recent Raspbian OS on a Raspberry Pi using mono.

### CODE REVIEW

**Comment by varunchopra** [comment]
Push this.

**Comment by shlnz** [comment]
@Devlix on my system (arch linux) it is still not building with your changes:
**_CSC: error CS2001: Source file `Exceptions/PtcOfflineException.cs' could not be found_**
You can find a full build log of xbuild [here](http://pastebin.com/9ngduNHn).

**Comment by christoabrown** [comment]
@shlnz I fixed the source file reference but you also have to do a NuGet restore to get the assembly references for the project. Download NuGet.exe from https://github.com/NuGet/Home/releases and run `mono NuGet.exe restore` from the .sln directory before running xbuild.

**Comment by ghost** [comment]
I have a raspberry pi running fresh raspbian.  I did a clone of the repo then downloaded the NuGet.exe (3.3) and ran mono NuGet.exe restore as suggested by Devlix, followed by xbuild with the sln file and it keeps failing.

Am I doing something wrong here?  seems like pretty basic steps but maybe I'm missing something?

**Comment by shlnz** [comment]
@Devlix Thank you for your suggestion. Now all *.dll files are in the _FeroxRev/PokemonGo.RocketAPI/bin/Debug_ folder, but `xbuild` still fails with the same error. Do you have any ideas what I could also try?

**Comment by christoabrown** [comment]
@shlnz Did you download the new commit? I had to rename a file because linux seems to treat case-sensitivity on file names differently.

**Comment by shlnz** [comment]
@Devlix Oh sweet. It compiles, many thanks!

**Comment by ghost** [comment]
@shlnz did you just clone the repo then run the mono NuGet.exe then xbuild "Haxton PokemonGo Bot.sln"?

**Comment by shlnz** [comment]
@Skrowp yes, my steps were:
`git clone https://github.com/Devlix/HaxtonBot.git`
`cd HaxtonBot`
`cp /path/to/NuGet.exe .`
`mono NuGet.exe restore`
`xbuild`

**Comment by ghost** [comment]
@Devlix I've been trying on an rpi 1.  I did a clean install of raspbian then did `sudo apt-get update` and `sudo apt-get upgrade`.  Followed by `sudo apt-get install mono-complete`.   I cloned the repo using shlnz's clone command and download the NuGet.exe using `wget https://github.com/NuGet/Home/releases/download/3.3/NuGet.exe`.  Then when I run `mono NuGet.exe restore` I get errors telling me it can't find a bunch of dependencies: Google.Protobuf, Google.Protobuf.Tools, VarintBitConverter, EnterpriseLibrary.TransientFaultHandling ,POGOProtos, GPSOAuthSharp, C5, NLog, Newtonsoft.Json, System.Device.Location.Portable.

Do you have any suggestions or ideas what I might be doing wrong?

**Comment by christoabrown** [comment]
@Skrowp Could you post a log of the output you are getting?

**Comment by ghost** [comment]
@Devlix Sure, here's the results from `mono NuGet.exe restore`:

> MSBuild auto-detection: using msbuild version '4.0' from '/usr/lib/mono/4.5'.
> Feeds used:
>   /root/.local/share/NuGet/Cache
>   https://api.nuget.org/v3/index.json
> 
> Restoring NuGet package C5.2.2.5073.27396.
> Restoring NuGet package EnterpriseLibrary.TransientFaultHandling.6.0.1304.
> Restoring NuGet package EnterpriseLibrary.TransientFaultHandling.Data.6.0.1304.1.
> Restoring NuGet package Google.Protobuf.3.0.0-beta4.
> Restoring NuGet package Google.Protobuf.Tools.3.0.0-beta3.
> Restoring NuGet package GPSOAuthSharp.0.0.5.
> Restoring NuGet package Microsoft.AspNet.WebApi.Client.5.2.3.
> Restoring NuGet package Newtonsoft.Json.9.0.1.
> Restoring NuGet package POGOProtos.1.3.0.
> Restoring NuGet package S2Geometry.1.0.1.
> Restoring NuGet package VarintBitConverter.1.0.0.
> Restoring NuGet package Google.Protobuf.Tools.3.0.0-beta4.
> Restoring NuGet package morelinq.1.4.0.
> Restoring NuGet package NLog.4.4.0-betaV15.
> Restoring NuGet package POGOProtos.1.4.0.
> Restoring NuGet package System.Device.Location.Portable.1.0.0.
> WARNING: Unable to find version '3.0.0-beta4' of package 'Google.Protobuf'.
> Restoring NuGet package NLog.4.3.6.
> WARNING: Unable to find version '1.4.0' of package 'POGOProtos'.
> Restoring NuGet package structuremap.4.2.0.402.
> WARNING: Unable to find version '3.0.0-beta3' of package 'Google.Protobuf.Tools'.
> WARNING: Unable to find version '1.4.0' of package 'morelinq'.
> WARNING: Unable to find version '2.2.5073.27396' of package 'C5'.
> WARNING: Unable to find version '6.0.1304.1' of package 'EnterpriseLibrary.TransientFaultHandling.Data'.
> WARNING: Unable to find version '5.2.3' of package 'Microsoft.AspNet.WebApi.Client'.
> WARNING: Unable to find version '0.0.5' of package 'GPSOAuthSharp'.
> WARNING: Unable to find version '1.0.0' of package 'System.Device.Location.Portable'.
> WARNING: Unable to find version '6.0.1304' of package 'EnterpriseLibrary.TransientFaultHandling'.
> WARNING: Unable to find version '1.0.1' of package 'S2Geometry'.
> WARNING: Unable to find version '1.3.0' of package 'POGOProtos'.
> WARNING: Unable to find version '9.0.1' of package 'Newtonsoft.Json'.
> WARNING: Unable to find version '4.2.0.402' of package 'structuremap'.
> WARNING: Unable to find version '1.0.0' of package 'VarintBitConverter'.
> WARNING: Unable to find version '4.3.6' of package 'NLog'.
> WARNING: Unable to find version '3.0.0-beta4' of package 'Google.Protobuf.Tools'.
> WARNING: Unable to find version '4.4.0-betaV15' of package 'NLog'.
> Unable to find version '6.0.1304.1' of package 'EnterpriseLibrary.TransientFaultHandling.Data'.
> Unable to find version '1.0.0' of package 'System.Device.Location.Portable'.
> Unable to find version '3.0.0-beta4' of package 'Google.Protobuf.Tools'.
> Unable to find version '2.2.5073.27396' of package 'C5'.
> Unable to find version '3.0.0-beta4' of package 'Google.Protobuf'.
> Unable to find version '1.4.0' of package 'POGOProtos'.
> Unable to find version '3.0.0-beta3' of package 'Google.Protobuf.Tools'.
> Unable to find version '1.4.0' of package 'morelinq'.
> Unable to find version '4.3.6' of package 'NLog'.
> Unable to find version '6.0.1304' of package 'EnterpriseLibrary.TransientFaultHandling'.
> Unable to find version '4.2.0.402' of package 'structuremap'.
> Unable to find version '1.0.0' of package 'VarintBitConverter'.
> Unable to find version '1.3.0' of package 'POGOProtos'.
> Unable to find version '4.4.0-betaV15' of package 'NLog'.
> Unable to find version '5.2.3' of package 'Microsoft.AspNet.WebApi.Client'.
> Unable to find version '0.0.5' of package 'GPSOAuthSharp'.
> Unable to find version '1.0.1' of package 'S2Geometry'.
> Unable to find version '9.0.1' of package 'Newtonsoft.Json'.

**Comment by christoabrown** [comment]
@Skrowp try running `mozroots --sync --import` to update mono's root certificates.

**Comment by ghost** [comment]
@Devlix I can't get that command to run either. It tries downloading from some mxr.mozilla.org source then says 

> Couldn't retrieve the file using the supplied information

**Comment by christoabrown** [comment]
@Skrowp maybe you could try `sudo apt-get install ca-certificates-mono` to see if that is installed and
`sudo certmgr -ssl -m https://go.microsoft.com`
`sudo certmgr -ssl -m https://nugetgallery.blob.core.windows.net`
`sudo certmgr -ssl -m https://nuget.org`

**Comment by ghost** [comment]
I switched to an ubuntu system and got further but now when i try running the console with `mono PokemonGo.Haxton.Console.exe` get this error:

> Unhandled Exception:
> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
> Parameter name: instance 'PokemonGo.Haxton.Bot.Inventory.PoGoInventory' with ReturnType PokemonGo.Haxton.Bot.Inventory.PoGoInventory cannot be cast to PokemonGo.Haxton.Bot.Inventory.IPoGoInventory
>   at StructureMap.Graph.PluginFamily.assertInstanceIsValidForThisPluginType (StructureMap.Pipeline.Instance instance) <0x41858c80 + 0x00163> in <filename unknown>:0
>   at StructureMap.Graph.PluginFamily.AddInstance (StructureMap.Pipeline.Instance instance) <0x41858be0 + 0x00027> in <filename unknown>:0
>   at StructureMap.Graph.PluginFamily.SetDefault (StructureMap.Pipeline.Instance instance) <0x41858a10 + 0x00077> in <filename unknown>:0
>   at StructureMap.Configuration.DSL.Expressions.CreatePluginFamilyExpression`1+<>c__DisplayClass47_0[TPluginType].<registerDefault>b__0 (StructureMap.Graph.PluginFamily family) <0x4185f4b0 + 0x00023> in <filename unknown>:0
>   at StructureMap.Configuration.DSL.Expressions.CreatePluginFamilyExpression`1+<>c__DisplayClass3_0[TPluginType].<.ctor>b__2 (System.Action`1 action) <0x4185f480 + 0x0001d> in <filename unknown>:0
>   at StructureMap.StringExtensions.Each[T] (IEnumerable`1 enumerable, System.Action`1 action) <0x4185ed10 + 0x00078> in <filename unknown>:0
>   at StructureMap.Configuration.DSL.Expressions.CreatePluginFamilyExpression`1[TPluginType].<.ctor>b__3_0 (StructureMap.Graph.PluginGraph graph) <0x4185ef80 + 0x002c3> in <filename unknown>:0
>   at StructureMap.Registry+<>c__DisplayClass18_0.<Configure>b__0 (System.Action`1 action) <0x4185ef40 + 0x0001d> in <filename unknown>:0
>   at StructureMap.StringExtensions.Each[T] (IEnumerable`1 enumerable, System.Action`1 action) <0x4185ed10 + 0x00078> in <filename unknown>:0
>   at StructureMap.Registry.Configure (StructureMap.Graph.PluginGraph graph) <0x4185ebc0 + 0x00117> in <filename unknown>:0
>   at StructureMap.PluginGraphBuilder.RunConfigurations () <0x4185e0f0 + 0x0026b> in <filename unknown>:0
>   at StructureMap.PluginGraphBuilder.Build () <0x4185df60 + 0x00017> in <filename unknown>:0
>   at StructureMap.ConfigurationExpression.BuildGraph () <0x4185dec0 + 0x0001b> in <filename unknown>:0
>   at StructureMap.PipelineGraph.For (System.Action`1 action) <0x41855120 + 0x00053> in <filename unknown>:0
>   at StructureMap.Container..ctor (System.Action`1 action) <0x418550e0 + 0x00017> in <filename unknown>:0
>   at PokemonGo.Haxton.Console.Program.Main (System.String[] args) <0x41854620 + 0x00187> in <filename unknown>:0
> 
> Unhandled Exception:
> System.NullReferenceException: Object reference not set to an instance of an object
>   at PokemonGo.Haxton.Console.Program.Main (System.String[] args) <0x41854620 + 0x00767> in <filename unknown>:0
> [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
>   at PokemonGo.Haxton.Console.Program.Main (System.String[] args) <0x41854620 + 0x00767> in <filename unknown>:0

**Comment by shlnz** [comment]
Take a look at this [issue]: https://github.com/d-haxton/HaxtonBot/issues/78. I had the same problem

**Comment by ghost** [comment]
@shlnz thanks a lot that did the trick.

**Pull request merged**
